### ISSUE TITLE
Service Workers: Go Offline or Go Home

### ISSUE THREAD

**Issue by yvesgurcan** [eugenewebdevs/giving-a-talk#13]
We'll explore what service workers are and how to implement them in your applications. The talk will include use cases, details on the benefits and caveats of using service workers, and info on Workbox (a Google library to facilitate the usage of workers). We will also explore the Cache API and how you can create an experience close to (or even better than) native mobile apps with service workers.

**Comment by antonioortegajr** [comment]
title "Service Workers: Go Offline or Go Home"

**Comment by antonioortegajr** [comment]
done
